// /** @type {import('tailwindcss').Config} */

const colors = require('tailwindcss/colors');

module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts,scss}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      black: '#000000',
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
      colorPrimary: 'var(--color-primary)',
      colorPrimaryLighter: 'var(--color-primary-lighter)',
      colorPrimaryDarker: 'var(--color-primary-darker)',
      colorSecondary: 'var(--color-secondary)',
      colorSecondaryLihter: 'var(--color-secondary-lighter)',
      colorSecondaryDarker: 'var(--color-secondary-darker)',
      colorSuccess: 'var(--color-success)',
      colorDangerous: 'var(--color-dangerous)',
      colorWarning: 'var(--color-warning)',
      backgroundDark: 'var(--background-dark)',
      backgroundLight: 'var(--background-light)',
      backgroundComponentDark: 'var(--background-component-dark)',
      backgroundComponentDarkLighter: 'var(--background-component-dark-lighter)',
      backgroundComponentLight: 'var(--background-component-light)',
      backgroundComponentLightDarker: 'var(--background-component-light-darker)',
    },
    extend: {},
  },
  plugins: ['tailwindcss/nesting'],
};
